//! Disaster-recovery endpoints.
//!
//! `POST /api/admin/backup/servers/:id/recover` — pull ALL photos from a
//! backup server and re‐register them locally (admin only).
//!
//! `GET /api/admin/backup/servers/:id/photos` — proxy/browse a backup
//! server's photo list through this server (avoids CORS issues in the UI).
//!
//! **Design notes:**
//! - Recovery first restores **user accounts** (with full credentials and
//!   2FA) from the backup so that per-user photo ownership is preserved and
//!   users can log in immediately on the restored server.
//! - Recovery deduplicates by **photo ID** and **file_path** — if the local
//!   DB already has a row with the same primary key *or* the same file_path,
//!   the photo is skipped. This prevents duplicates when a backup server
//!   has photos from a prior scan (different UUIDs, same on-disk files).
//! - Recovered photos preserve their original `user_id` from the backup.
//!   If the referenced user wasn't restored (e.g. recovery was partial),
//!   the photo falls back to the admin who triggered recovery.
//! - All metadata columns are preserved: `is_favorite`, `camera_model`,
//!   `photo_hash`, `crop_metadata`.
//! - Thumbnails are not downloaded — they will be regenerated by the
//!   background converter on the next cycle.
//! - Encrypted blob IDs and encryption metadata are NOT transferred —
//!   recovery restores the on-disk files only.

use axum::extract::{Path, State};
use axum::http::StatusCode;
use axum::Json;
use chrono::Utc;
use uuid::Uuid;

use crate::auth::middleware::AuthUser;
use crate::error::AppError;
use crate::sanitize;
use crate::setup::admin::require_admin;
use crate::state::AppState;

use super::models::*;
use super::sync::try_acquire_sync;

// ── Recovery ─────────────────────────────────────────────────────────────────

/// POST /api/admin/backup/servers/:id/recover
/// Recover all photos from a backup server that don't already exist locally.
/// Runs as a background task; returns immediately with a recovery_id.
///
/// This endpoint:
/// 1. Connects to the backup server's /api/backup/list endpoint
/// 2. Deduplicates by **photo ID** against the local `photos` table
/// 3. Downloads any missing photos and stores them locally
/// 4. Registers them in the photos table (INSERT OR IGNORE for idempotency)
pub async fn recover_from_backup(
    State(state): State<AppState>,
    auth: AuthUser,
    Path(server_id): Path<String>,
) -> Result<(StatusCode, Json<RecoveryResponse>), AppError> {
    require_admin(&state, &auth).await?;

    // Fetch backup server details
    let server = sqlx::query_as::<_, BackupServer>(
        "SELECT id, name, address, sync_frequency_hours, last_sync_at, \
         last_sync_status, last_sync_error, enabled, created_at \
         FROM backup_servers WHERE id = ?",
    )
    .bind(&server_id)
    .fetch_optional(&state.pool)
    .await?
    .ok_or(AppError::NotFound)?;

    // Fetch the API key for the remote server
    let api_key: Option<String> =
        sqlx::query_scalar("SELECT api_key FROM backup_servers WHERE id = ?")
            .bind(&server_id)
            .fetch_optional(&state.pool)
            .await?
            .flatten();

    // Create a sync log entry for tracking
    let recovery_id = Uuid::new_v4().to_string();
    let now = Utc::now().to_rfc3339();
    let server_name = server.name.clone();

    sqlx::query(
        "INSERT INTO backup_sync_log (id, server_id, started_at, status) \
         VALUES (?, ?, ?, 'recovering')",
    )
    .bind(&recovery_id)
    .bind(&server_id)
    .bind(&now)
    .execute(&state.pool)
    .await?;

    // Prevent overlapping recoveries to the same server
    let guard = try_acquire_sync(&server_id).ok_or_else(|| {
        AppError::BadRequest("A sync or recovery is already in progress for this server".into())
    })?;

    // Spawn recovery as a background task (guard moves into the task
    // so the lock is held for the full duration and released on drop).
    let pool = state.pool.clone();
    let storage_root = (**state.storage_root.load()).clone();
    let user_id = auth.user_id.clone();
    let recovery_id_clone = recovery_id.clone();

    tokio::spawn(async move {
        let _guard = guard; // hold lock until task completes
        run_recovery(
            &pool,
            &storage_root,
            &server,
            &api_key,
            &user_id,
            &recovery_id_clone,
        )
        .await;
    });

    Ok((
        StatusCode::ACCEPTED,
        Json(RecoveryResponse {
            message: format!("Recovery from '{}' started", server_name),
            recovery_id,
        }),
    ))
}

/// Execute the actual recovery from a backup server.
///
/// **Phase 1 — Users:** Pulls all user accounts (with credentials and 2FA)
/// from the backup via `GET /api/backup/list-users-full` and upserts them
/// locally. This ensures per-user photo ownership is preserved and users
/// can log in on the restored server immediately.
///
/// **Phase 2 — Photos:** Downloads all photos not already present locally
/// (by ID or file_path), preserving the original `user_id`. Falls back to
/// the admin's ID only when the referenced user doesn't exist locally.
async fn run_recovery(
    pool: &sqlx::SqlitePool,
    storage_root: &std::path::Path,
    server: &BackupServer,
    api_key: &Option<String>,
    admin_user_id: &str,
    recovery_id: &str,
) {
    let client = match reqwest::Client::builder()
        .timeout(std::time::Duration::from_secs(300))
        .danger_accept_invalid_certs(true)
        .build()
    {
        Ok(c) => c,
        Err(e) => {
            update_recovery_log(pool, recovery_id, "error", 0, 0, Some(&e.to_string())).await;
            return;
        }
    };

    let base_url = format!("http://{}/api", server.address);

    // ── Phase 1: Restore user accounts ──────────────────────────────────
    let users_restored = recover_users(pool, &client, &base_url, api_key, &server.name).await;
    tracing::info!(
        "Recovery from '{}': restored {} user account(s)",
        server.name,
        users_restored
    );

    // Build a set of locally-known user IDs so we can validate ownership
    // when inserting photos. If the original owner doesn't exist locally
    // (e.g. partial recovery), we fall back to the admin.
    let local_user_ids: std::collections::HashSet<String> =
        match sqlx::query_scalar::<_, String>("SELECT id FROM users")
            .fetch_all(pool)
            .await
        {
            Ok(ids) => ids.into_iter().collect(),
            Err(e) => {
                tracing::warn!("Recovery: failed to query local users: {}", e);
                std::collections::HashSet::new()
            }
        };

    // ── Phase 2: Restore photos ─────────────────────────────────────────

    // Fetch remote photo list
    let mut list_req = client.get(format!("{}/backup/list", base_url));
    if let Some(ref key) = api_key {
        list_req = list_req.header("X-API-Key", key.as_str());
    }

    let remote_photos: Vec<BackupPhotoRecord> = match list_req.send().await {
        Ok(resp) if resp.status().is_success() => match resp.json().await {
            Ok(photos) => photos,
            Err(e) => {
                update_recovery_log(
                    pool,
                    recovery_id,
                    "error",
                    0,
                    0,
                    Some(&format!("Failed to parse backup photo list: {}", e)),
                )
                .await;
                return;
            }
        },
        Ok(resp) => {
            update_recovery_log(
                pool,
                recovery_id,
                "error",
                0,
                0,
                Some(&format!("Backup server returned HTTP {}", resp.status())),
            )
            .await;
            return;
        }
        Err(e) => {
            update_recovery_log(
                pool,
                recovery_id,
                "error",
                0,
                0,
                Some(&format!("Failed to connect to backup server: {}", e)),
            )
            .await;
            return;
        }
    };

    tracing::info!(
        "Recovery from '{}': found {} photos on backup",
        server.name,
        remote_photos.len()
    );

    // Get local photo IDs AND file_paths for deduplication.
    //   ID dedup handles re-recovery of the same backup.
    //   file_path dedup prevents re-downloading files that were registered
    //   by a local scan (different ID, same on-disk file).
    let local_entries: Vec<(String, String)> =
        match sqlx::query_as::<_, (String, String)>("SELECT id, file_path FROM photos")
            .fetch_all(pool)
            .await
        {
            Ok(rows) => rows,
            Err(e) => {
                update_recovery_log(pool, recovery_id, "error", 0, 0, Some(&e.to_string())).await;
                return;
            }
        };

    let local_id_set: std::collections::HashSet<String> =
        local_entries.iter().map(|(id, _)| id.clone()).collect();
    let local_path_set: std::collections::HashSet<String> =
        local_entries.iter().map(|(_, fp)| fp.clone()).collect();

    // Filter to photos not already on this server (by ID or file_path)
    let missing: Vec<&BackupPhotoRecord> = remote_photos
        .iter()
        .filter(|p| !local_id_set.contains(&p.id) && !local_path_set.contains(&p.file_path))
        .collect();

    tracing::info!(
        "Recovery from '{}': {} photos to download ({} already exist locally by ID or file_path)",
        server.name,
        missing.len(),
        remote_photos.len() - missing.len()
    );

    let mut photos_recovered = 0i64;
    let mut bytes_recovered = 0i64;

    // Download and register each missing photo
    for photo in &missing {
        let mut dl_req = client.get(format!("{}/backup/download/{}", base_url, photo.id));
        if let Some(ref key) = api_key {
            dl_req = dl_req.header("X-API-Key", key.as_str());
        }

        let file_data = match dl_req.send().await {
            Ok(resp) if resp.status().is_success() => match resp.bytes().await {
                Ok(bytes) => bytes,
                Err(e) => {
                    tracing::warn!(
                        "Recovery: failed to read bytes for {}: {}",
                        photo.filename,
                        e
                    );
                    continue;
                }
            },
            Ok(resp) => {
                tracing::warn!(
                    "Recovery: backup returned HTTP {} for photo {}",
                    resp.status(),
                    photo.filename
                );
                continue;
            }
            Err(e) => {
                tracing::warn!("Recovery: download failed for {}: {}", photo.filename, e);
                continue;
            }
        };

        // Determine storage path — use the original file_path from the backup.
        // SECURITY: validate the remote-supplied path to prevent directory traversal.
        let file_path = &photo.file_path;
        if let Err(reason) = sanitize::validate_relative_path(file_path) {
            tracing::warn!(
                "Recovery: skipping {} — unsafe file_path '{}': {}",
                photo.filename,
                file_path,
                reason
            );
            continue;
        }
        let full_path = storage_root.join(file_path);

        // Ensure parent directory exists
        if let Some(parent) = full_path.parent() {
            if let Err(e) = tokio::fs::create_dir_all(parent).await {
                tracing::warn!("Recovery: failed to create dir for {}: {}", file_path, e);
                continue;
            }
        }

        // Write file to disk
        if let Err(e) = tokio::fs::write(&full_path, &file_data).await {
            tracing::warn!("Recovery: failed to write {}: {}", file_path, e);
            continue;
        }

        // Preserve original user_id if the user exists locally; fall back to admin.
        let effective_user_id = if local_user_ids.contains(&photo.user_id) {
            &photo.user_id
        } else {
            tracing::debug!(
                "Recovery: user_id '{}' not found locally for photo {}; assigning to admin",
                photo.user_id,
                photo.id
            );
            admin_user_id
        };

        // Register in the photos table — preserve the original photo ID from
        // the backup so delta-sync and re-recovery can deduplicate correctly.
        // ON CONFLICT(id) DO NOTHING makes re-runs idempotent.
        // The WHERE NOT EXISTS guard prevents creating a duplicate row when
        // the same file_path already exists under a different local ID
        // (e.g. registered by a local scan between pre-filter and INSERT).
        let now = Utc::now().to_rfc3339();
        let thumb_filename = format!("{}.thumb.jpg", photo.id);
        let thumb_rel = format!(".thumbnails/{}", thumb_filename);

        let result = sqlx::query(
            "INSERT OR IGNORE INTO photos (id, user_id, filename, file_path, mime_type, media_type, \
             size_bytes, width, height, duration_secs, taken_at, latitude, longitude, \
             thumb_path, created_at, is_favorite, camera_model, photo_hash, crop_metadata) \
             SELECT ?1, ?2, ?3, ?4, ?5, ?6, ?7, ?8, ?9, ?10, ?11, ?12, ?13, ?14, ?15, ?16, ?17, ?18, ?19 \
             WHERE NOT EXISTS (SELECT 1 FROM photos WHERE file_path = ?4)",
        )
        .bind(&photo.id)           // ?1
        .bind(effective_user_id)    // ?2
        .bind(&photo.filename)     // ?3
        .bind(file_path)           // ?4
        .bind(&photo.mime_type)    // ?5
        .bind(&photo.media_type)   // ?6
        .bind(file_data.len() as i64) // ?7
        .bind(photo.width)         // ?8
        .bind(photo.height)        // ?9
        .bind(photo.duration_secs) // ?10
        .bind(&photo.taken_at)     // ?11
        .bind(photo.latitude)      // ?12
        .bind(photo.longitude)     // ?13
        .bind(&thumb_rel)          // ?14
        .bind(&now)                // ?15
        .bind(photo.is_favorite)   // ?16
        .bind(&photo.camera_model) // ?17
        .bind(&photo.photo_hash)   // ?18
        .bind(&photo.crop_metadata) // ?19
        .execute(pool)
        .await;

        match result {
            Err(e) => {
                tracing::warn!("Recovery: failed to register {}: {}", photo.filename, e);
                // Clean up the written file on DB failure
                let _ = tokio::fs::remove_file(&full_path).await;
                continue;
            }
            Ok(res) if res.rows_affected() == 0 => {
                // Row was skipped (ID conflict or file_path already exists).
                // Remove the file we just wrote — we don't need it.
                let _ = tokio::fs::remove_file(&full_path).await;
                continue;
            }
            Ok(_) => {}
        }

        photos_recovered += 1;
        bytes_recovered += file_data.len() as i64;
    }

    // Update recovery log
    update_recovery_log(
        pool,
        recovery_id,
        "success",
        photos_recovered,
        bytes_recovered,
        None,
    )
    .await;

    tracing::info!(
        "Recovery from '{}' complete: {} user(s), {} photos, {} bytes recovered",
        server.name,
        users_restored,
        photos_recovered,
        bytes_recovered
    );
}

// ── User Recovery Helper ─────────────────────────────────────────────────────

/// Pull all user accounts from a backup server and upsert them locally.
/// Returns the number of users successfully restored.
///
/// Uses `GET /api/backup/list-users-full` which returns full credentials
/// (password_hash, totp_secret, totp_enabled, totp_backup_codes).
/// Each user is upserted via INSERT ... ON CONFLICT(id) DO UPDATE so
/// re-running recovery is idempotent and won't clobber local changes
/// if the user already exists.
async fn recover_users(
    pool: &sqlx::SqlitePool,
    client: &reqwest::Client,
    base_url: &str,
    api_key: &Option<String>,
    server_name: &str,
) -> usize {
    let mut req = client.get(format!("{}/backup/list-users-full", base_url));
    if let Some(ref key) = api_key {
        req = req.header("X-API-Key", key.as_str());
    }

    let remote_users: Vec<serde_json::Value> = match req.send().await {
        Ok(resp) if resp.status().is_success() => match resp.json().await {
            Ok(users) => users,
            Err(e) => {
                tracing::warn!(
                    "Recovery from '{}': failed to parse user list: {} — skipping user restore",
                    server_name,
                    e
                );
                return 0;
            }
        },
        Ok(resp) => {
            // Graceful degradation: if the backup doesn't support this endpoint
            // (older version), log a warning and continue to photo recovery.
            tracing::warn!(
                "Recovery from '{}': list-users-full returned HTTP {} — \
                 skipping user restore (backup may be running an older version)",
                server_name,
                resp.status()
            );
            return 0;
        }
        Err(e) => {
            tracing::warn!(
                "Recovery from '{}': failed to fetch users: {} — skipping user restore",
                server_name,
                e
            );
            return 0;
        }
    };

    tracing::info!(
        "Recovery from '{}': found {} user account(s) on backup",
        server_name,
        remote_users.len()
    );

    let mut restored = 0usize;
    for user in &remote_users {
        let id = match user.get("id").and_then(|v| v.as_str()) {
            Some(v) => v,
            None => continue,
        };
        let username = match user.get("username").and_then(|v| v.as_str()) {
            Some(v) => v,
            None => continue,
        };
        let password_hash = match user.get("password_hash").and_then(|v| v.as_str()) {
            Some(v) => v,
            None => continue,
        };
        let role = user
            .get("role")
            .and_then(|v| v.as_str())
            .unwrap_or("user");
        let quota = user
            .get("storage_quota_bytes")
            .and_then(|v| v.as_i64())
            .unwrap_or(10_737_418_240);
        let created_at = user
            .get("created_at")
            .and_then(|v| v.as_str())
            .unwrap_or("");
        let totp_secret: Option<&str> = user.get("totp_secret").and_then(|v| v.as_str());
        let totp_enabled: i32 = user
            .get("totp_enabled")
            .and_then(|v| v.as_i64())
            .unwrap_or(0) as i32;

        // Upsert user — ON CONFLICT(id) preserves existing local user if
        // already present, but updates credentials to match the backup.
        let result = sqlx::query(
            "INSERT INTO users (id, username, password_hash, created_at, storage_quota_bytes, \
             role, totp_secret, totp_enabled) \
             VALUES (?, ?, ?, ?, ?, ?, ?, ?) \
             ON CONFLICT(id) DO UPDATE SET \
                 username            = excluded.username, \
                 password_hash       = excluded.password_hash, \
                 role                = excluded.role, \
                 storage_quota_bytes = excluded.storage_quota_bytes, \
                 totp_secret         = excluded.totp_secret, \
                 totp_enabled        = excluded.totp_enabled",
        )
        .bind(id)
        .bind(username)
        .bind(password_hash)
        .bind(created_at)
        .bind(quota)
        .bind(role)
        .bind(totp_secret)
        .bind(totp_enabled)
        .execute(pool)
        .await;

        if let Err(e) = result {
            // Username collision (different id, same username) — skip
            // rather than risk data loss during recovery.
            tracing::warn!(
                "Recovery: failed to restore user '{}' (id={}): {}",
                username,
                id,
                e
            );
            continue;
        }

        // Restore TOTP backup codes
        if let Some(codes) = user.get("totp_backup_codes").and_then(|v| v.as_array()) {
            // Clear existing codes for this user first (idempotent re-runs)
            let _ = sqlx::query("DELETE FROM totp_backup_codes WHERE user_id = ?")
                .bind(id)
                .execute(pool)
                .await;

            for code in codes {
                let code_id = match code.get("id").and_then(|v| v.as_str()) {
                    Some(c) => c,
                    None => continue,
                };
                let code_hash = match code.get("code_hash").and_then(|v| v.as_str()) {
                    Some(c) => c,
                    None => continue,
                };
                let used = code.get("used").and_then(|v| v.as_i64()).unwrap_or(0) as i32;

                let _ = sqlx::query(
                    "INSERT OR REPLACE INTO totp_backup_codes (id, user_id, code_hash, used) \
                     VALUES (?, ?, ?, ?)",
                )
                .bind(code_id)
                .bind(id)
                .bind(code_hash)
                .bind(used)
                .execute(pool)
                .await;
            }
        }

        restored += 1;
    }

    restored
}

/// Update the sync log entry used for tracking recovery progress.
async fn update_recovery_log(
    pool: &sqlx::SqlitePool,
    log_id: &str,
    status: &str,
    photos_synced: i64,
    bytes_synced: i64,
    error: Option<&str>,
) {
    let now = Utc::now().to_rfc3339();
    if let Err(e) = sqlx::query(
        "UPDATE backup_sync_log SET completed_at = ?, status = ?, photos_synced = ?, \
         bytes_synced = ?, error = ? WHERE id = ?",
    )
    .bind(&now)
    .bind(status)
    .bind(photos_synced)
    .bind(bytes_synced)
    .bind(error)
    .bind(log_id)
    .execute(pool)
    .await
    {
        tracing::error!("Failed to update recovery log {}: {}", log_id, e);
    }
}

// ── Backup View Proxy ────────────────────────────────────────────────────────

/// GET /api/admin/backup/servers/:id/photos
/// Proxy endpoint: fetches the photo list from a backup server and returns it.
/// Used by the frontend to show a backup view of photos.
pub async fn proxy_backup_photos(
    State(state): State<AppState>,
    auth: AuthUser,
    Path(server_id): Path<String>,
) -> Result<Json<Vec<BackupPhotoRecord>>, AppError> {
    require_admin(&state, &auth).await?;

    let address: String = sqlx::query_scalar("SELECT address FROM backup_servers WHERE id = ?")
        .bind(&server_id)
        .fetch_optional(&state.pool)
        .await?
        .ok_or(AppError::NotFound)?;

    let api_key: Option<String> =
        sqlx::query_scalar("SELECT api_key FROM backup_servers WHERE id = ?")
            .bind(&server_id)
            .fetch_optional(&state.pool)
            .await?
            .flatten();

    let client = reqwest::Client::builder()
        .timeout(std::time::Duration::from_secs(30))
        .build()
        .map_err(|e| AppError::BadRequest(format!("HTTP client error: {}", e)))?;

    let mut req = client.get(format!("http://{}/api/backup/list", address));
    if let Some(ref key) = api_key {
        req = req.header("X-API-Key", key.as_str());
    }

    match req.send().await {
        Ok(resp) if resp.status().is_success() => {
            let photos: Vec<BackupPhotoRecord> = resp.json().await.map_err(|e| {
                AppError::BadRequest(format!("Failed to parse backup server response: {}", e))
            })?;
            Ok(Json(photos))
        }
        Ok(resp) => {
            let status = resp.status();
            let body = resp.text().await.unwrap_or_default();
            tracing::warn!(
                "Backup server at {} returned HTTP {}: {}",
                address,
                status,
                body
            );
            Err(AppError::BadRequest(format!(
                "Backup server returned HTTP {}",
                status
            )))
        }
        Err(e) => {
            tracing::warn!("Failed to connect to backup server at {}: {}", address, e);
            Err(AppError::BadRequest(format!(
                "Cannot reach backup server at {}: {}",
                address, e
            )))
        }
    }
}

/// GET /api/admin/backup/servers/:id/photos/:photo_id/thumb
/// Proxy endpoint: streams a thumbnail from a backup server through this
/// server to the browser, avoiding CORS restrictions.
pub async fn proxy_backup_thumbnail(
    State(state): State<AppState>,
    auth: AuthUser,
    Path((server_id, photo_id)): Path<(String, String)>,
) -> Result<axum::response::Response, AppError> {
    require_admin(&state, &auth).await?;

    let address: String = sqlx::query_scalar("SELECT address FROM backup_servers WHERE id = ?")
        .bind(&server_id)
        .fetch_optional(&state.pool)
        .await?
        .ok_or(AppError::NotFound)?;

    let api_key: Option<String> =
        sqlx::query_scalar("SELECT api_key FROM backup_servers WHERE id = ?")
            .bind(&server_id)
            .fetch_optional(&state.pool)
            .await?
            .flatten();

    let client = reqwest::Client::builder()
        .timeout(std::time::Duration::from_secs(15))
        .build()
        .map_err(|e| AppError::BadRequest(format!("HTTP client error: {}", e)))?;

    let url = format!("http://{}/api/backup/download/{}/thumb", address, photo_id);
    let mut req = client.get(&url);
    if let Some(ref key) = api_key {
        req = req.header("X-API-Key", key.as_str());
    }

    match req.send().await {
        Ok(resp) if resp.status().is_success() => {
            let content_type = resp
                .headers()
                .get("content-type")
                .and_then(|v| v.to_str().ok())
                .unwrap_or("image/jpeg")
                .to_string();

            let bytes = resp
                .bytes()
                .await
                .map_err(|e| AppError::BadRequest(format!("Failed to read thumbnail: {}", e)))?;

            Ok(axum::response::Response::builder()
                .status(axum::http::StatusCode::OK)
                .header("Content-Type", content_type)
                .header("Cache-Control", "private, max-age=3600")
                .body(axum::body::Body::from(bytes))
                .map_err(|e| AppError::Internal(format!("Failed to build response: {}", e)))?)
        }
        Ok(resp) if resp.status() == axum::http::StatusCode::NOT_FOUND => Err(AppError::NotFound),
        Ok(resp) => Err(AppError::BadRequest(format!(
            "Backup server returned HTTP {} for thumbnail",
            resp.status()
        ))),
        Err(e) => Err(AppError::BadRequest(format!(
            "Cannot reach backup server for thumbnail: {}",
            e
        ))),
    }
}
