//! Disaster-recovery endpoints.
//!
//! `POST /api/admin/backup/servers/:id/recover` — pull ALL photos from a
//! backup server and re‐register them locally (admin only).
//!
//! `GET /api/admin/backup/servers/:id/photos` — proxy/browse a backup
//! server's photo list through this server (avoids CORS issues in the UI).
//!
//! **Design notes:**
//! - Recovery deduplicates by **photo ID** and **file_path** — if the local
//!   DB already has a row with the same primary key *or* the same file_path,
//!   the photo is skipped. This prevents duplicates when a backup server
//!   has photos from a prior scan (different UUIDs, same on-disk files).
//! - All recovered photos are assigned to the admin who triggers the
//!   recovery; original per-user ownership is lost.
//! - Thumbnails are not downloaded — they will be regenerated by the
//!   background converter on the next cycle.
//! - Encrypted blob IDs and encryption metadata are NOT transferred —
//!   recovery is effectively plain-mode only.

use axum::extract::{Path, State};
use axum::http::StatusCode;
use axum::Json;
use chrono::Utc;
use uuid::Uuid;

use crate::auth::middleware::AuthUser;
use crate::error::AppError;
use crate::sanitize;
use crate::setup::admin::require_admin;
use crate::state::AppState;

use super::models::*;
use super::sync::try_acquire_sync;

// ── Recovery ─────────────────────────────────────────────────────────────────

/// POST /api/admin/backup/servers/:id/recover
/// Recover all photos from a backup server that don't already exist locally.
/// Runs as a background task; returns immediately with a recovery_id.
///
/// This endpoint:
/// 1. Connects to the backup server's /api/backup/list endpoint
/// 2. Deduplicates by **photo ID** against the local `photos` table
/// 3. Downloads any missing photos and stores them locally
/// 4. Registers them in the photos table (INSERT OR IGNORE for idempotency)
pub async fn recover_from_backup(
    State(state): State<AppState>,
    auth: AuthUser,
    Path(server_id): Path<String>,
) -> Result<(StatusCode, Json<RecoveryResponse>), AppError> {
    require_admin(&state, &auth).await?;

    // Fetch backup server details
    let server = sqlx::query_as::<_, BackupServer>(
        "SELECT id, name, address, sync_frequency_hours, last_sync_at, \
         last_sync_status, last_sync_error, enabled, created_at \
         FROM backup_servers WHERE id = ?",
    )
    .bind(&server_id)
    .fetch_optional(&state.pool)
    .await?
    .ok_or(AppError::NotFound)?;

    // Fetch the API key for the remote server
    let api_key: Option<String> = sqlx::query_scalar(
        "SELECT api_key FROM backup_servers WHERE id = ?",
    )
    .bind(&server_id)
    .fetch_optional(&state.pool)
    .await?
    .flatten();

    // Create a sync log entry for tracking
    let recovery_id = Uuid::new_v4().to_string();
    let now = Utc::now().to_rfc3339();
    let server_name = server.name.clone();

    sqlx::query(
        "INSERT INTO backup_sync_log (id, server_id, started_at, status) \
         VALUES (?, ?, ?, 'recovering')",
    )
    .bind(&recovery_id)
    .bind(&server_id)
    .bind(&now)
    .execute(&state.pool)
    .await?;

    // Prevent overlapping recoveries to the same server
    let guard = try_acquire_sync(&server_id).ok_or_else(|| {
        AppError::BadRequest(
            "A sync or recovery is already in progress for this server".into(),
        )
    })?;

    // Spawn recovery as a background task (guard moves into the task
    // so the lock is held for the full duration and released on drop).
    let pool = state.pool.clone();
    let storage_root = (**state.storage_root.load()).clone();
    let user_id = auth.user_id.clone();
    let recovery_id_clone = recovery_id.clone();

    tokio::spawn(async move {
        let _guard = guard; // hold lock until task completes
        run_recovery(
            &pool,
            &storage_root,
            &server,
            &api_key,
            &user_id,
            &recovery_id_clone,
        )
        .await;
    });

    Ok((
        StatusCode::ACCEPTED,
        Json(RecoveryResponse {
            message: format!("Recovery from '{}' started", server_name),
            recovery_id,
        }),
    ))
}

/// Execute the actual recovery from a backup server.
/// Downloads all photos that don't already exist locally (by photo ID).
async fn run_recovery(
    pool: &sqlx::SqlitePool,
    storage_root: &std::path::Path,
    server: &BackupServer,
    api_key: &Option<String>,
    user_id: &str,
    recovery_id: &str,
) {
    let client = match reqwest::Client::builder()
        .timeout(std::time::Duration::from_secs(300))
        .build()
    {
        Ok(c) => c,
        Err(e) => {
            update_recovery_log(pool, recovery_id, "error", 0, 0, Some(&e.to_string())).await;
            return;
        }
    };

    let base_url = format!("http://{}/api", server.address);

    // 1. Fetch remote photo list
    let mut list_req = client.get(format!("{}/backup/list", base_url));
    if let Some(ref key) = api_key {
        list_req = list_req.header("X-API-Key", key.as_str());
    }

    let remote_photos: Vec<BackupPhotoRecord> = match list_req.send().await {
        Ok(resp) if resp.status().is_success() => match resp.json().await {
            Ok(photos) => photos,
            Err(e) => {
                update_recovery_log(
                    pool,
                    recovery_id,
                    "error",
                    0,
                    0,
                    Some(&format!("Failed to parse backup photo list: {}", e)),
                )
                .await;
                return;
            }
        },
        Ok(resp) => {
            update_recovery_log(
                pool,
                recovery_id,
                "error",
                0,
                0,
                Some(&format!(
                    "Backup server returned HTTP {}",
                    resp.status()
                )),
            )
            .await;
            return;
        }
        Err(e) => {
            update_recovery_log(
                pool,
                recovery_id,
                "error",
                0,
                0,
                Some(&format!("Failed to connect to backup server: {}", e)),
            )
            .await;
            return;
        }
    };

    tracing::info!(
        "Recovery from '{}': found {} photos on backup",
        server.name,
        remote_photos.len()
    );

    // 2. Get local photo IDs AND file_paths for deduplication.
    //    ID dedup handles re-recovery of the same backup.
    //    file_path dedup prevents re-downloading files that were registered
    //    by a local scan (different ID, same on-disk file).
    let local_entries: Vec<(String, String)> = match sqlx::query_as::<_, (String, String)>(
        "SELECT id, file_path FROM photos",
    )
    .fetch_all(pool)
    .await
    {
        Ok(rows) => rows,
        Err(e) => {
            update_recovery_log(pool, recovery_id, "error", 0, 0, Some(&e.to_string())).await;
            return;
        }
    };

    let local_id_set: std::collections::HashSet<String> =
        local_entries.iter().map(|(id, _)| id.clone()).collect();
    let local_path_set: std::collections::HashSet<String> =
        local_entries.iter().map(|(_, fp)| fp.clone()).collect();

    // 3. Filter to photos not already on this server (by ID or file_path)
    let missing: Vec<&BackupPhotoRecord> = remote_photos
        .iter()
        .filter(|p| !local_id_set.contains(&p.id) && !local_path_set.contains(&p.file_path))
        .collect();

    tracing::info!(
        "Recovery from '{}': {} photos to download ({} already exist locally by ID or file_path)",
        server.name,
        missing.len(),
        remote_photos.len() - missing.len()
    );

    let mut photos_recovered = 0i64;
    let mut bytes_recovered = 0i64;

    // 4. Download and register each missing photo
    for photo in &missing {
        // Download the file from the backup
        let mut dl_req = client.get(format!("{}/backup/download/{}", base_url, photo.id));
        if let Some(ref key) = api_key {
            dl_req = dl_req.header("X-API-Key", key.as_str());
        }

        let file_data = match dl_req.send().await {
            Ok(resp) if resp.status().is_success() => match resp.bytes().await {
                Ok(bytes) => bytes,
                Err(e) => {
                    tracing::warn!("Recovery: failed to read bytes for {}: {}", photo.filename, e);
                    continue;
                }
            },
            Ok(resp) => {
                tracing::warn!(
                    "Recovery: backup returned HTTP {} for photo {}",
                    resp.status(),
                    photo.filename
                );
                continue;
            }
            Err(e) => {
                tracing::warn!("Recovery: download failed for {}: {}", photo.filename, e);
                continue;
            }
        };

        // Determine storage path — use the original file_path from the backup.
        // SECURITY: validate the remote-supplied path to prevent directory traversal.
        let file_path = &photo.file_path;
        if let Err(reason) = sanitize::validate_relative_path(file_path) {
            tracing::warn!(
                "Recovery: skipping {} — unsafe file_path '{}': {}",
                photo.filename, file_path, reason
            );
            continue;
        }
        let full_path = storage_root.join(file_path);

        // Ensure parent directory exists
        if let Some(parent) = full_path.parent() {
            if let Err(e) = tokio::fs::create_dir_all(parent).await {
                tracing::warn!("Recovery: failed to create dir for {}: {}", file_path, e);
                continue;
            }
        }

        // Write file to disk
        if let Err(e) = tokio::fs::write(&full_path, &file_data).await {
            tracing::warn!("Recovery: failed to write {}: {}", file_path, e);
            continue;
        }

        // Register in the photos table — preserve the original photo ID from
        // the backup so delta-sync and re-recovery can deduplicate correctly.
        // ON CONFLICT(id) DO NOTHING makes re-runs idempotent.
        // The WHERE NOT EXISTS guard prevents creating a duplicate row when
        // the same file_path already exists under a different local ID
        // (e.g. registered by a local scan between pre-filter and INSERT).
        let now = Utc::now().to_rfc3339();
        let thumb_filename = format!("{}.thumb.jpg", photo.id);
        let thumb_rel = format!(".thumbnails/{}", thumb_filename);

        let result = sqlx::query(
            "INSERT OR IGNORE INTO photos (id, user_id, filename, file_path, mime_type, media_type, \
             size_bytes, width, height, duration_secs, taken_at, latitude, longitude, \
             thumb_path, created_at) \
             SELECT ?1, ?2, ?3, ?4, ?5, ?6, ?7, ?8, ?9, ?10, ?11, ?12, ?13, ?14, ?15 \
             WHERE NOT EXISTS (SELECT 1 FROM photos WHERE file_path = ?4)",
        )
        .bind(&photo.id)
        .bind(user_id)
        .bind(&photo.filename)
        .bind(file_path)
        .bind(&photo.mime_type)
        .bind(&photo.media_type)
        .bind(file_data.len() as i64)
        .bind(photo.width)
        .bind(photo.height)
        .bind(photo.duration_secs)
        .bind(&photo.taken_at)
        .bind(photo.latitude)
        .bind(photo.longitude)
        .bind(&thumb_rel)
        .bind(&now)
        .execute(pool)
        .await;

        match result {
            Err(e) => {
                tracing::warn!("Recovery: failed to register {}: {}", photo.filename, e);
                // Clean up the written file on DB failure
                let _ = tokio::fs::remove_file(&full_path).await;
                continue;
            }
            Ok(res) if res.rows_affected() == 0 => {
                // Row was skipped (ID conflict or file_path already exists).
                // Remove the file we just wrote — we don't need it.
                let _ = tokio::fs::remove_file(&full_path).await;
                continue;
            }
            Ok(_) => {}
        }

        photos_recovered += 1;
        bytes_recovered += file_data.len() as i64;
    }

    // 5. Update recovery log
    update_recovery_log(
        pool,
        recovery_id,
        "success",
        photos_recovered,
        bytes_recovered,
        None,
    )
    .await;

    tracing::info!(
        "Recovery from '{}' complete: {} photos, {} bytes recovered",
        server.name,
        photos_recovered,
        bytes_recovered
    );
}

/// Update the sync log entry used for tracking recovery progress.
async fn update_recovery_log(
    pool: &sqlx::SqlitePool,
    log_id: &str,
    status: &str,
    photos_synced: i64,
    bytes_synced: i64,
    error: Option<&str>,
) {
    let now = Utc::now().to_rfc3339();
    if let Err(e) = sqlx::query(
        "UPDATE backup_sync_log SET completed_at = ?, status = ?, photos_synced = ?, \
         bytes_synced = ?, error = ? WHERE id = ?",
    )
    .bind(&now)
    .bind(status)
    .bind(photos_synced)
    .bind(bytes_synced)
    .bind(error)
    .bind(log_id)
    .execute(pool)
    .await
    {
        tracing::error!("Failed to update recovery log {}: {}", log_id, e);
    }
}

// ── Backup View Proxy ────────────────────────────────────────────────────────

/// GET /api/admin/backup/servers/:id/photos
/// Proxy endpoint: fetches the photo list from a backup server and returns it.
/// Used by the frontend to show a backup view of photos.
pub async fn proxy_backup_photos(
    State(state): State<AppState>,
    auth: AuthUser,
    Path(server_id): Path<String>,
) -> Result<Json<Vec<BackupPhotoRecord>>, AppError> {
    require_admin(&state, &auth).await?;

    let address: String = sqlx::query_scalar(
        "SELECT address FROM backup_servers WHERE id = ?",
    )
    .bind(&server_id)
    .fetch_optional(&state.pool)
    .await?
    .ok_or(AppError::NotFound)?;

    let api_key: Option<String> = sqlx::query_scalar(
        "SELECT api_key FROM backup_servers WHERE id = ?",
    )
    .bind(&server_id)
    .fetch_optional(&state.pool)
    .await?
    .flatten();

    let client = reqwest::Client::builder()
        .timeout(std::time::Duration::from_secs(30))
        .build()
        .map_err(|e| AppError::Internal(format!("HTTP client error: {}", e)))?;

    let mut req = client.get(format!("http://{}/api/backup/list", address));
    if let Some(ref key) = api_key {
        req = req.header("X-API-Key", key.as_str());
    }

    match req.send().await {
        Ok(resp) if resp.status().is_success() => {
            let photos: Vec<BackupPhotoRecord> = resp
                .json()
                .await
                .map_err(|e| AppError::Internal(format!("Failed to parse response: {}", e)))?;
            Ok(Json(photos))
        }
        Ok(resp) => Err(AppError::Internal(format!(
            "Backup server returned HTTP {}",
            resp.status()
        ))),
        Err(e) => Err(AppError::Internal(format!(
            "Failed to connect to backup server: {}",
            e
        ))),
    }
}
