#!/usr/bin/env python3
"""Generate a set of **geotagged sample photos** that exercise every edge case
of the smart location-album pipeline (Trips / Memories / precise addresses),
and drop them in the desktop sample-files folder so you can import them into a
running Simple-Photos server and SEE the albums appear.

Why this exists
---------------
"Memories never show up" is almost never a bug in the clustering code — it is a
stack of easy-to-miss preconditions:

  1. Geolocation must be ENABLED for your user (Settings → Geolocation; it is
     OFF by default for privacy).
  2. Photos must carry GPS EXIF  → the server fills latitude/longitude.
  3. Photos must carry a date     → the server fills taken_at; Trips & Memories
     both filter ``taken_at IS NOT NULL``.
  4. Enough clustered photos:
        Trip   = >= 5 photos, same city, consecutive photos <= 3 days apart
        Memory = >= 3 photos, same city, same calendar day
  5. The GeoNames ``cities500.txt`` dataset must be present server-side.
  6. The background geo-processor poll cycle must run (every 5 min in prod).

These samples satisfy 2–4 for you with hand-picked coordinates and dates, and
each photo is captioned with the edge case it proves and the album you should
expect, so a human can verify the result by eye.

Usage
-----
    python scripts/generate_geo_samples.py
    python scripts/generate_geo_samples.py --out "D:/somewhere/geo"
    python scripts/generate_geo_samples.py --clean       # wipe the dir first

Then in the app:
    Settings → Geolocation → Enable.  (For the precise case, also enable
    "Precise Street Addresses".)  Import the folder, wait for the poll cycle,
    then open Albums → Trips / Memories.
"""

from __future__ import annotations

import argparse
import os
import sys

# Reuse the test-suite's fixtures + EXIF builders so the bytes the app parses
# are identical to what tests/test_86 asserts.
sys.path.insert(0, os.path.join(os.path.dirname(__file__), "..", "tests"))

from geo_fixtures import (  # noqa: E402
    GROUPS,
    EXPECT_IMPORT_DATED_MEMORY_COUNT,
    EXPECT_IMPORT_DATED_TRIP_COUNT,
    EXPECT_LOCATION_CITY_COUNT,
    EXPECT_MEMORY_PHOTO_COUNTS_DATED,
    EXPECT_TRIP_PHOTO_COUNTS_DATED,
    photo_bytes,
    total_photos,
)

# Totals a human should see in the app: the deterministic dated albums plus the
# one extra trip + memory the no-date group forms (dated to the import day).
TOTAL_TRIPS = len(EXPECT_TRIP_PHOTO_COUNTS_DATED) + 1
TOTAL_MEMORIES = len(EXPECT_MEMORY_PHOTO_COUNTS_DATED) + 1


def default_out() -> str:
    root = os.environ.get(
        "SAMPLE_FILES_ROOT", os.path.expanduser("~/Desktop/Sample_files")
    )
    return os.path.join(root, "geo")


README = """\
# Geolocation edge-case sample photos

Generated by `scripts/generate_geo_samples.py`. Each JPEG carries real GPS EXIF
(and, where relevant, a DateTimeOriginal) and is captioned with the edge case it
proves and the album you should expect.

## How to see the albums

1. **Settings -> Geolocation -> Enable.** (Geo is OFF by default for privacy;
   with it off, nothing here resolves and no albums appear.)
2. For the precise case, also enable **"Precise Street Addresses"** (sends only
   that photo's coordinates to OpenStreetMap/Photon; city-level stays offline).
3. **Import this whole folder.**
4. Wait for the background geo-processor (every ~5 min in production; sooner on
   a fresh server). The profile indicator spins while it resolves.
5. Open **Albums -> Trips** and **Albums -> Memories**.

## What to expect

| Group | Photos | Expected result |
|-------|-------:|-----------------|
{rows}

**Totals across the set:** {trips} Trip albums, {mems} Memory albums,
{cities} resolved locations.

## Negative cases (these must produce NO album — that's the point)

- `lisbon_below` - only 2 photos in a day -> no memory, no trip.
- `timeline_nogps` - a date but no GPS -> timeline only, never a location album.
- `ocean_sentinel` - mid-Pacific coordinates resolve to no city -> stored, but
  never an album (and must not wedge the resolver at "resolving... forever").

## Surprising-but-correct case

- `sydney_nodate` - GPS but NO EXIF date. The server never stores a NULL
  timestamp: it stamps `taken_at` with the import time. So these 5 photos
  cluster into a trip + memory dated to **whenever you import them**, not to
  when they were taken. Good to know if a batch of dateless geotagged photos
  suddenly shows up as a "trip" dated today.

If you enable geo, import these, wait a cycle, and the Trips/Memories sections
are still empty, the bug is real — capture the server log and check
`geo/processor.rs` (dataset path / poll cycle).
"""


def write_readme(out_dir: str) -> None:
    rows = []
    for g in GROUPS:
        rows.append(f"| `{g.key}` | {g.count} | {g.expect} |")
    text = README.format(
        rows="\n".join(rows),
        trips=TOTAL_TRIPS,
        mems=TOTAL_MEMORIES,
        cities=EXPECT_LOCATION_CITY_COUNT,
    )
    with open(os.path.join(out_dir, "README.md"), "w", encoding="utf-8") as f:
        f.write(text)


def main() -> int:
    ap = argparse.ArgumentParser(
        description=__doc__, formatter_class=argparse.RawDescriptionHelpFormatter
    )
    ap.add_argument("--out", default=default_out(),
                    help="Output directory (default: %(default)s)")
    ap.add_argument("--clean", action="store_true",
                    help="Remove existing *.jpg in the output dir first")
    args = ap.parse_args()

    os.makedirs(args.out, exist_ok=True)
    if args.clean:
        for fn in os.listdir(args.out):
            if fn.lower().endswith(".jpg"):
                os.remove(os.path.join(args.out, fn))

    seq = 0
    written = 0
    for g in GROUPS:
        for idx in range(g.count):
            data = photo_bytes(g, idx, seq, captioned=True)
            name = f"{seq:02d}_{g.key}_{idx + 1}.jpg"
            with open(os.path.join(args.out, name), "wb") as f:
                f.write(data)
            seq += 1
            written += 1
        print(f"  [{g.key:16s}] {g.count} photo(s)  -> {g.expect}")

    write_readme(args.out)

    print(f"\nWrote {written} photos (expected {total_photos()}) to:\n  {args.out}")
    print(f"\nExpected once geo is enabled and resolved:")
    print(f"  Trips    : {TOTAL_TRIPS}  "
          f"(dated {EXPECT_TRIP_PHOTO_COUNTS_DATED} + 1 import-dated "
          f"[{EXPECT_IMPORT_DATED_TRIP_COUNT}] from the no-date group)")
    print(f"  Memories : {TOTAL_MEMORIES}  "
          f"(dated {EXPECT_MEMORY_PHOTO_COUNTS_DATED} + 1 import-dated "
          f"[{EXPECT_IMPORT_DATED_MEMORY_COUNT}] from the no-date group)")
    print(f"  Locations: {EXPECT_LOCATION_CITY_COUNT} resolved cities")
    print("\nSee README.md in that folder for how to enable geo and verify.")
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
