-- Persist the encryption key (wrapped by a server-side secret) so the server
-- can resume encryption migration autonomously after a restart or browser close.
--
-- The key is AES-256-GCM encrypted using a key derived from the JWT secret
-- before it is stored. It is only present while a migration is pending or
-- recently completed; it is cleared once migration finishes and the grace
-- period expires.
--
-- Uses the existing server_settings table (no new tables needed).
-- Key: 'encryption_key_wrapped'  Value: hex-encoded wrapped key blob
-- Key: 'encryption_key_active'   Value: 'true' if key should be loaded on startup
